config/routes.rb
Lairbnb::Application.routes.draw do
  resources :listings
  devise_for :users
  resources :users
  root to: "users#index"

end

app/models/event.rb
class Event < ActiveRecord::Base
  has_event_calendar
end

app/models/listing.rb
class Listing < ActiveRecord::Base
  belongs_to :user
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  paginates_per 5

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  after_create :send_welcome_message
  has_many :listings

  def send_welcome_message
    UserMailer.deliver_welcome_message(self).deliver
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/calendar_controller.rb
class CalendarController < ApplicationController
  
  def index
    @month = (params[:month] || (Time.zone || Time).now.month).to_i
    @year = (params[:year] || (Time.zone || Time).now.year).to_i

    @shown_month = Date.civil(@year, @month)

    @event_strips = Event.event_strips_for_month(@shown_month)
  end
  
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  def create
  @listing = Listing.create(listing_params)
  respond_to do |format|
    format.html {redirect_to listings_path}
    format.js
  end
end

  def new
    @listing = Listing.new
  end

  def show
    @listing = Listing.find(params[:id])

  end

  def index
    @listing = Listing.all.page(params[:page]).per(5)

  end

  def edit
    @listing = Listing.find(params[:id])
  end

  def update
    redirect_to listings_path
  end

  def destroy
    @listing = Listing.find(params[:id])
    @listing.destroy
    redirect_to listings_path
  end

  private
  def listing_params
    params.require(:listing).permit(:avatar, :name, :content, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @user = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_url, notice: "Thanks for signing up!"
    else render "new"
    end
  end



  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
  def month_link(month_date)
    link_to(I18n.localize(month_date, :format => "%B"), {:month => month_date.month, :year => month_date.year})
  end
  
  # custom options for this calendar
  def event_calendar_opts
    { 
      :year => @year,
      :month => @month,
      :event_strips => @event_strips,
      :month_name_text => I18n.localize(@shown_month, :format => "%B %Y"),
      :previous_month_text => "<< " + month_link(@shown_month.prev_month),
      :next_month_text => month_link(@shown_month.next_month) + " >>"    }
  end

  def event_calendar
    # args is an argument hash containing :event, :day, and :options
    calendar event_calendar_opts do |args|
      event = args[:event]
      %(<a href="/events/#{event.id}" title="#{h(event.name)}">#{h(event.name)}</a>)
    end
  end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/calendar/index.html.erb
<!-- Probably move the stylesheet to you layout. Also make sure you include the javascript. -->
<%= stylesheet_link_tag "event_calendar" %>

<h1>Calendar</h1>

<%= raw(event_calendar) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Evil Lairs and Headquarters for Rent -Lairbnb</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <link href='http://fonts.googleapis.com/css?family=Cutive' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Cookie' rel='stylesheet' type='text/css'>

  <%= csrf_meta_tags %>
</head>
<body>
  <div id="container">
  <div id="user_nav">
    <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to 'Edit profile', edit_user_registration_path %> | <span>
      <%= link_to "Logout", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path %> |
      <%= link_to "Login", new_user_session_path %>
    <% end %>
  </div>

  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, id: "flash_#{name}" %>
  <% end %>

  <%= yield %>
</div>

</body>
</html>

app/views/listings/_form.html.erb
<div id="new_listing">
  <%= form_for @listing, remote: true do |f| %>
    <%= f.label :name %> <br>
    <%= f.text_area :name %><br>
    <%= f.label :content %> <br>
    <%= f.text_area :content %><br>
    <%= f.hidden_field :user_id, :value => session[:user_id] %><br>
    <div class="field">
      <%= f.label :avatar %><br>
      <%= f.file_field :avatar %><br>
    </div>
    <%= f.submit(:class => 'classname') %>
  <% end %>
</div>

app/views/listings/create.js.erb
$('#new_listing').remove();
$('#new_listing').show();
$('#all_listing').append('<%= render(@listing) %>');

app/views/listings/edit.html.erb
<div id="edit_listing">
  <%= form_for @listing, :html => { :multipart => true } do |f| %>
    <%= f.label :name %> <br>
    <%= f.text_area :name %><br>
    <%= f.label :content %> <br>
    <%= f.text_area :content %><br>
    <%= f.hidden_field :user_id, :value => session[:user_id] %><br>
    <div class="field">
      <%= f.label :avatar %><br>
      <%= f.file_field :avatar %><br>
    </div>
    <%= f.submit(:class => 'classname') %>
  <% end %>
</div>

app/views/listings/index.html.erb
<div class="top-logo">
<h1>LairBnb</h1>
<h2>"Your Evil Vacation HeadQuarters Rental Service"</h2>
</div>



<div class="container">
  <div class="main-content">
    <span><img src="http://i32.tinypic.com/2jcauli.jpg"></span>
    <span><img src="http://i29.tinypic.com/23ly0hs.jpg"></span>
    <span><img src="http://i32.tinypic.com/1073qpx.jpg"></span>

  </div>
   <%= link_to "Add a Listing", new_listing_path, id: "new_listing", remote: true %>

<%= paginate @listing %>

</div>

<div id="all_listing">
  <ul>
    <% Listing.all.each do |listing| %>
    <li><%= link_to listing.name, listing_path(listing) %><br><%= listing.content %><br><%= image_tag listing.avatar(:thumb) %></li></a>
    <% end %>
  </ul>
</div>

app/views/listings/new.html.erb
<%= form_for @listing, :url => listings_path, :html => { :multipart => true } do |form| %>
  <%= form.file_field :avatar %>
<% end %>

app/views/listings/new.js.erb
$('#new_link').hide().after('<%= j render("form") %>');

app/views/listings/show.html.erb
<h1><%= @listing.name %></h1>
<%= image_tag @listing.avatar.url(:medium) %>

<p><%= @listing.content %></p>

<p><%= link_to "Edit Info", edit_listing_path %></p>
<%= link_to ("Delete Listing"), listing_path(@listing), method: "delete" %>

app/views/users/_form.html.erb
<div id="new_listing">
  <%= form_for @listing, remote: true do |f| %>
    <%= f.label :name %> <br>
    <%= f.text_area :name %><br>
    <%= f.label :content %> <br>
    <%= f.text_area :content %><br>
    <%= f.hidden_field :user_id, :value => session[:user_id] %><br>
    <div class="field">
      <%= f.label :avatar %><br>
      <%= f.file_field :avatar %><br>
    </div>
    <%= f.submit(:class => 'classname') %>
  <% end %>
</div>

app/views/users/index.html.erb
<div class="top-logo">
<h1>LairBnb</h1>
<h2>"Your Evil Vacation HeadQuarters Rental Service"</h2>
</div>

<div class="container">
  <div class="main-content">
    <span><img src="http://i32.tinypic.com/2jcauli.jpg"></span>
    <span><img src="http://i29.tinypic.com/23ly0hs.jpg"></span>
    <span><img src="http://i32.tinypic.com/1073qpx.jpg"></span>

  </div>
   <%= link_to "Add a Listing", new_listing_path, id: "new_link", remote: true %>



</div>

app/views/users/new.js.erb
$('#new_listing').hide().after('<%= j render("form") %>');